version: "3"

services:
  apache:
    build:
      context: .
    container_name: apache
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    restart: always
    env_file: .env
    ports:
      - "1000:80"
    depends_on:
      - mysql

  mysql:
    image: yobasystems/alpine-mariadb
    ports:
      - "5000:3306"
    container_name: mysql
    # volumes:
    #   - ./mysqlvolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lara_db
      MYSQL_USER: lara_user
      MYSQL_PASSWORD: pass
    restart: always
